### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import random

import numpy as np

In [2]:
vector_1 = np.array([random.uniform(0, 1) for _ in range(10)])

print(vector_1)
print(vector_1.shape)

[0.1995013  0.77751901 0.14037905 0.27840753 0.25296743 0.62703093
 0.59509034 0.5459189  0.02135788 0.75653824]
(10,)


In [3]:
vector_2 = np.random.rand(10)

print(vector_2)
print(vector_2.shape)

[0.715571   0.20881617 0.65367802 0.21002849 0.22329612 0.48254942
 0.0497665  0.04507872 0.55419682 0.66520926]
(10,)


In [4]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print(matrix)
print(matrix.shape)

[[11 14 17]
 [20 23 26]
 [29 32 35]]
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [5]:
vector_plus_10_rounded = (vector_1 + 10).round(2)

matrix_times_2 = matrix * 2

vector_squared = vector_1**2

print(vector_plus_10_rounded)
print(matrix_times_2)
print(vector_squared)

[10.2  10.78 10.14 10.28 10.25 10.63 10.6  10.55 10.02 10.76]
[[22 28 34]
 [40 46 52]
 [58 64 70]]
[3.98007692e-02 6.04535805e-01 1.97062786e-02 7.75107548e-02
 6.39925230e-02 3.93167791e-01 3.54132509e-01 2.98027449e-01
 4.56159221e-04 5.72350116e-01]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [6]:
A = np.array([[0.18, 0.53], [0.75, 0.47], [0.35, 0.21]])

B = np.array([[0.17, 0.58, 0.75], [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0, 1], [1, 0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [7]:
result_matrix = np.dot(B, A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [8]:
result_matrix_mult_C = np.dot(result_matrix, C)
print(result_matrix_mult_C)

[[0.5202]
 [0.2846]]


In [9]:
result_matrix_mult_D = np.dot(result_matrix, D)
print(result_matrix_mult_D)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [10]:
result_matrix_T = result_matrix.T
print(result_matrix_T)

vector_1_T = vector_1.T
print(vector_1_T)
print(vector_1.shape)
print(vector_1_T.shape)


column_vector = np.expand_dims(vector_1, axis=1)
print(column_vector)
print(column_vector.shape)

column_vector_T = column_vector.T
print(column_vector_T)
print(column_vector_T.shape)

[[0.7281 0.2034]
 [0.5202 0.2846]]
[0.1995013  0.77751901 0.14037905 0.27840753 0.25296743 0.62703093
 0.59509034 0.5459189  0.02135788 0.75653824]
(10,)
(10,)
[[0.1995013 ]
 [0.77751901]
 [0.14037905]
 [0.27840753]
 [0.25296743]
 [0.62703093]
 [0.59509034]
 [0.5459189 ]
 [0.02135788]
 [0.75653824]]
(10, 1)
[[0.1995013  0.77751901 0.14037905 0.27840753 0.25296743 0.62703093
  0.59509034 0.5459189  0.02135788 0.75653824]]
(1, 10)
